load("@rules_compdb//:defs.bzl", "compilation_database")
load("@bazel_output_base_util//:defs.bzl", "OUTPUT_BASE")

compilation_database(
    name = "compdb",
    targets = [
        "//api:main",
    ],
)
